### ISSUE TITLE
fix: `governanceBatch.build()` throws at end of deploy

### ISSUE THREAD

**Issue by anna-carroll** [nomad-xyz/monorepo#146]
seems like something while creating the governance batches is not adding / connecting RPC signers properly. 

when I run the deploy script, it throws with: 
```
/Users/anna/code/nomad/monorepo/packages/sdk/src/CoreContracts.ts:61
      throw new Error('No provider or signer. Call `connect` first.');
            ^
Error: No provider or signer. Call `connect` first.
    at CoreContracts.get governanceRouter [as governanceRouter] (/Users/anna/code/nomad/monorepo/packages/sdk/src/CoreContracts.ts:61:13)
    at CallBatch.<anonymous> (/Users/anna/code/nomad/monorepo/packages/sdk-govern/src/index.ts:148:31)
    at Generator.next (<anonymous>)
    at /Users/anna/code/nomad/monorepo/packages/sdk-govern/dist/index.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/anna/code/nomad/monorepo/packages/sdk-govern/dist/index.js:27:12)
    at CallBatch.build (/Users/anna/code/nomad/monorepo/packages/sdk-govern/dist/index.js:128:16)
    at /Users/anna/code/nomad/monorepo/packages/new-deploy/scripts/deploy.ts:48:29
    at Generator.next (<anonymous>)
    at fulfilled (/Users/anna/code/nomad/monorepo/packages/new-deploy/scripts/deploy.ts:28:58)
```

then, i tested fixing it by adding this line to `CallBatch.build()` before calling `this.governorCore.governanceRouter`: 
```
    await this.governorCore.connect(this.context.mustGetConnection(this.governorCore.domain));
```
and it threw with: 
```
/Users/anna/code/nomad/monorepo/packages/multi-provider/src/provider.ts:357
      throw new NoProviderError(this, nameOrDomain);
            ^
NoProviderError: Missing provider for domain: 2000 : rinkeby
    at NomadContext.mustGetConnection (/Users/anna/code/nomad/monorepo/packages/multi-provider/src/provider.ts:357:13)
    at CallBatch.<anonymous> (/Users/anna/code/nomad/monorepo/packages/sdk-govern/src/index.ts:147:50)
    at Generator.next (<anonymous>)
    at /Users/anna/code/nomad/monorepo/packages/sdk-govern/dist/index.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/anna/code/nomad/monorepo/packages/sdk-govern/dist/index.js:27:12)
    at CallBatch.build (/Users/anna/code/nomad/monorepo/packages/sdk-govern/dist/index.js:128:16)
    at /Users/anna/code/nomad/monorepo/packages/new-deploy/scripts/deploy.ts:48:29
    at Generator.next (<anonymous>)
    at fulfilled (/Users/anna/code/nomad/monorepo/packages/new-deploy/scripts/deploy.ts:28:58) {
  provider: NomadContext {
    domains: Map(3) {
      'kovan' => [Object],
      'xdai' => [Object],
      'rinkeby' => [Object]
    },
    providers: Map(0) {},
    signers: Map(0) {},
    conf: {
      version: 0,
      environment: 'development',
      networks: [Array],
      rpcs: [Object],
      protocol: [Object],
      core: [Object],
      bridge: [Object],
      agent: [Object],
      bridgeGui: {}
    },
    _cores: Map(3) {
      'kovan' => [CoreContracts],
      'xdai' => [CoreContracts],
      'rinkeby' => [CoreContracts]
    },
    _blacklist: Set(0) {}
  },
  domain: 'rinkeby',
  domainName: 'rinkeby',
  domainNumber: 2000
}
```

**Comment by anna-carroll** [comment]
closed by https://github.com/nomad-xyz/monorepo/pull/147
